### ISSUE TITLE
Move Enumeration.js to phet-core

### ISSUE THREAD

**Issue by samreid** [phetsims/phet-core#40]
From last week's dev meeting:

> JO: I keep running into cases where it would be nice to have a non-sim-specific “Orientation” enumeration (horizontal/vertical). Is this something that would be desired? Should I look into commonizing area-model’s implementation?
JO & SR will discuss later on

area-model-common/js/common/model/Orientation.js seems too specific to area-model.

'FRACTIONS_COMMON/common/enum/Enumeration' looks great and it would work seamlessly with PhET-iO because it's all based on strings instead of object identity.

Want to move 'FRACTIONS_COMMON/common/enum/Enumeration' to phet-core?  If we did that, would there be a need to factor out types like fractions-common/js/intro/view/enum/NumberLineOrientation.js ?

**Comment by zepumph** [comment]
While we are at it, it seems like a good idea to make that generic Enumeration type common as well. I find myself adding the same boilerplate to all my enums: freezing if assert is enabled, storing the keys on the object too. It would be good it that was factored out and consistent (sometimes I name by keys `keys` instead of `VALUES`.

**Comment by jonathanolson** [comment]
Added Enumeration to phet-core. Would either of you like to review?

**Comment by zepumph** [comment]
I have nothing more to add that isn't covered by https://github.com/phetsims/phet-core/issues/42. Usages look good. Ready to close?

**Comment by jonathanolson** [comment]
Sure, that issue definitely sounds like the place for further improvements/discussion. Thanks!
