### ISSUE TITLE
merge doesn't work with null sources

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phet-core#74]
Related to #71 

`merge` is failing to handle `null` sources properly.  See console example below. 

This is important for parameterized calls like `merge( {...}, paramOptions )` where `paramOptions` may have a null value.  It's also important to be compatible with `_.extend` if (as #71 says) we're going to globally replace `_.extend` with `merge`.   And I encountered this in the real world (vector-addition), so it's not a contrived example. 

```
> _.extend( {}, null )
{}
> phet.phetCore.merge( {}, null )
assert.js?bust=1570824155235:21 Assertion failed: Object should be truthy, an object, and cannot have an extra prototype
assert.js?bust=1570824155235:22 Uncaught Error: Assertion failed: Object should be truthy, an object, and cannot have an extra prototype
    at window.assertions.assertFunction (assert.js?bust=1570824155235:22)
    at validateMergeableObject (merge.js?bust=1570824155311:61)
    at merge.js?bust=1570824155311:33
    at u (lodash-4.17.4.min.js?bust=1570824155311:5)
    at Function.ru (lodash-4.17.4.min.js?bust=1570824155311:67)
    at Namespace.merge (merge.js?bust=1570824155311:31)
    at <anonymous>:1:15
```

**Comment by pixelzoom** [comment]
`merge( {}, null )` should also be added as a passing test case to merge.js.

**Comment by pixelzoom** [comment]
I'll bet this was broken by #73, where `_.filter` was replaced by `if ( source !== undefined )`. `_.filter` removes values that are not truthy, and that is not limited to `undefined`.   So `if ( source !== undefined )` should be `if ( source )`.

**Comment by pixelzoom** [comment]
For the same reasons as `merge( {}, null )`, I also don't agree that this should be a failing case, as shown in mergeTests.js:

```
> phet.phetCore.merge( { xOptions: { test: 1 } }, { xOptions: null } )
Assertion failed: Object should be truthy, an object, and cannot have an extra prototype
```

**Comment by zepumph** [comment]
Everything you say I agree with. That said it is this way because of a developer meeting consensus (at least that is what I read at the top of https://github.com/phetsims/phet-info/issues/91#issuecomment-519652587). 

No matter, that was not a real-world example. This is. I'll change the usage and write tests to support it.

**Comment by zepumph** [comment]
Above I updated merge to support null in `*Options` and in sources. It will still error if `null` is the first arg. Please review @pixelzoom does this seem good to you?

**Comment by pixelzoom** [comment]
Quick review of commits looks good, and unit test cases are passing.

**Comment by pixelzoom** [comment]
> It will still error if null is the first arg.

This is a deviation from `_.extend` (see below) but hopefully no one is relying on it.

```
> _.extend( null, {} )
{}
```

**Comment by zepumph** [comment]
>This is a deviation from _.extend (see below) but hopefully no one is relying on it.

Right. I would go one step further and say that for phet code this seems like a bug to me, and we should be asserting out to catch these cases. 

Here are a few other examples of _.extend being more graceful than I think we should be:
![image](https://user-images.githubusercontent.com/6856943/66789656-03a40a80-ee99-11e9-8662-d68c91ba1942.png)

This helped to catch two bugs so far in
https://github.com/phetsims/phet-core/issues/71. 


Furthermore, if we find a case in which it is beneficial for null to be the first arg, we can always change it later. @pixelzoom if you agree please close. Otherwise recommend next steps.

**Comment by pixelzoom** [comment]
@zepumph said:
> I would go one step further and say that for phet code this seems like a bug to me, and we should be asserting out to catch these cases.

I agree.  Closing.
