### ISSUE TITLE
Create abstraction for event/dt/step pattern

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phet-core#9]
We want an API that will be useful for handling variable-DT situations. Notably, we want to create particles according to accumulated DT (multiple per frame or none in one frame), have their elapsed time correctly spaced out, and be created at a specific rate.

In that case, once created, we would be able to track the full DT values afterwards for model steps.

**Comment by jonathanolson** [comment]
Added above mentioned clarifications and notes, along with graphical representations of the example (hopefully visually explaining):

![screen shot 2017-02-01 at 10 41 02 pm](https://cloud.githubusercontent.com/assets/480878/22537365/9d235dbe-e8cf-11e6-991f-5278c603aec2.png)

@pixelzoom, can you review again? If one pass through the documentation is insufficient for understanding, it would help to have a call to (a) communicate the exact purpose and benefits, and (b) fix the lapses in documentation.

**Comment by pixelzoom** [comment]
I reviewed the documentation, corrected a couple of minor typos.  Looks good to me.  But as I mentioned in https://github.com/phetsims/phet-core/issues/9#issuecomment-67989401:

> I also have not had a need for this type of feature, so I may not be the most qualified to evaluate this feature or its implementation.

And that's still the case. I've never used EventTimer, so I wasn't able to review the documentation for accuracy/completeness, or determine whether it is useful in practice.  So I'd recommend having another developer review the documentation, someone with EventTimer experience (@samreid?)

**Comment by samreid** [comment]
I count 5 occurrences in Color Vision, 2 in Fluid Pressure and Flow (unpublished flow screen), 2 in Gravity and Orbits and 2 in Sugar and Salt Solutions (unpublished).

It is unclear why this is used in Gravity and Orbits.  @jessegreenberg can you help me understand?

The usage is currently like so:

```js
    // create a new photon every 1/120 seconds
    // @private
    this.eventTimer = new EventTimer( new EventTimer.ConstantEventModel( 120 ), function( timeElapsed ) {
      self.photonBeam.createPhoton( timeElapsed );
    } );
```

Even though it would be an inferior implementation, would it be a superior API to code it like so?

```js
    // create a new photon every 1/120 seconds
    // @private
    this.eventTimer = new ConstantEventTimer( 120, function( timeElapsed ) {
      self.photonBeam.createPhoton( timeElapsed );
    } );
```

That is, implement this pattern with subclasses of EventTimer instead of different strategies to plug in.

I reviewed the documentation and the implementation of step() and the usages in Color Vision and it seems to be in good shape.  I don't have any other recommendations or hesitation about broader usage. And I don't feel too strongly about the API issue above.  @jonathanolson thoughts?

**Comment by jonathanolson** [comment]
I think I slightly prefer the dependency injection-like style currently used, instead of sub-typing on one specific configurable aspect. Please re-open if that doesn't sound good!
