### ISSUE TITLE
phet-core depends on Tandem

### ISSUE THREAD

**Issue by zepumph** [phetsims/phet-core#92]
While discussing https://github.com/phetsims/axon/issues/361, we realized that there is a problem with having an IOType in phet-core. phet-core is not supposed to have any dependencies. 

@samreid and I discussed this, and felt like it was a problem, but we didn't really talk through any solutions very thoroughly. 

One idea we touched on is created a new repo that is basically `phet-core-that-can-have-tandem-in-it`. @samreid also thought perhaps we should move EnumerationIO to `tandem/`, but would Enumeration go to? It certainly doesn't belong there.

@samreid let me know what you think, and what priority you feel this is.

**Comment by jonathanolson** [comment]
I'd also like to float the possibility of combining repos a bit more as standard practice. Is there a reason we want to have those two code-bases separate? I'm not aware of any needs for "I want phet-core, but not tandem"... since tandem seems core to what we're doing.

**Comment by zepumph** [comment]
I guess having a separation, at least cognitively of what code is required to run PhET-iO infrastructure and what code isn't needed is getting more and more blurred by the day, but I'm not immediately excited by the idea of completely merging the two. `phet-core` to me seems like a library of items that basically serve as dependency-less, reusable, helper functions and code. `tandem` has a very clear boundary to me that it is solely in support of PhET-iO brand, but public and open source.

**Comment by samreid** [comment]
It is also advantageous tracking issues for phet-core and tandem separately.  Right now the only problematic dependency is that phet-core defines EnumerationIO, which imports:

```js
import IOType from '../../tandem/js/types/IOType.js';
import StateSchema from '../../tandem/js/types/StateSchema.js';
```

It would work to move EnumerationIO to tandem.  However, when I proposed this in https://github.com/phetsims/axon/issues/361#issuecomment-931719421 @zepumph recommended that EnumerationIO may need to be imported by Enumeration now or soon.  However that isn't a current need, and we may be able to treat Enumeration differently since it is a different kind of data type.  We could always move EnumerationIO to tandem now, then move it back once we need it back (hopefully never?). That would solve this layer of dependency problem.  I'd also like to mention that we may re-envision enumerations with TypeScript: https://github.com/phetsims/chipper/issues/1106

Also, regarding priority, I believe we have reasonable workarounds in place if we end up keeping EnumerationIO in phet-core longer.  My current recommended plan is: 
* Investigate enumerations with TypeScript
* Depending on how that goes, probably move EnumerationIO to tandem

**Comment by samreid** [comment]
phet-core no longer imports from tandem.  It is included in the script imports in the HTML Unit test harness, but that's the only tandem reference I can see at the moment. Closing.
